const CACHE = 'grungy-v2';
const PREFIX = 'grungy-';
const ASSETS = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "apple-touch-icon.png",
  "pwa-192.png",
  "pwa-512.png",
  "css/theme.css",
  "css/styles.css",
  "fonts/LobsterTwo-Bold.ttf",
  "images/ajax-loader.gif",
  "images/gear.svg",
  "images/grungy.jpg",
  "images/instructions.jpg",
  "js/caman.full.min.js",
  "js/touchswitch.js",
  "js/jqtouch.min.js",
  "js/jquery-1.11.0.min.js",
  "js/jqtouch-jquery.min.js",
  "js/jNotify.jquery.js",
  "js/filter-settings.js",
  "js/fastclick.js",
  "js/jquery.blockUI.js",
  "js/app.js",
  "js/pwa.js",
  "filters-inverted/border1.png",
  "filters-inverted/border10.png",
  "filters-inverted/border11.png",
  "filters-inverted/border12.png",
  "filters-inverted/border13.png",
  "filters-inverted/border14.png",
  "filters-inverted/border15.png",
  "filters-inverted/border16.png",
  "filters-inverted/border17.png",
  "filters-inverted/border18.png",
  "filters-inverted/border19.png",
  "filters-inverted/border2.png",
  "filters-inverted/border20.png",
  "filters-inverted/border21.png",
  "filters-inverted/border23.png",
  "filters-inverted/border24.png",
  "filters-inverted/border25.png",
  "filters-inverted/border3.png",
  "filters-inverted/border4.png",
  "filters-inverted/border5.png",
  "filters-inverted/border6.png",
  "filters-inverted/border7.png",
  "filters-inverted/border8.png",
  "filters-inverted/border9.png",
  "filters-inverted/burn1.png",
  "filters-inverted/burn10.png",
  "filters-inverted/burn11.png",
  "filters-inverted/burn12.png",
  "filters-inverted/burn13.png",
  "filters-inverted/burn14.png",
  "filters-inverted/burn15.png",
  "filters-inverted/burn16.png",
  "filters-inverted/burn17.png",
  "filters-inverted/burn18.png",
  "filters-inverted/burn19.png",
  "filters-inverted/burn2.png",
  "filters-inverted/burn20.png",
  "filters-inverted/burn21.png",
  "filters-inverted/burn23.png",
  "filters-inverted/burn24.png",
  "filters-inverted/burn25.png",
  "filters-inverted/burn3.png",
  "filters-inverted/burn4.png",
  "filters-inverted/burn5.png",
  "filters-inverted/burn6.png",
  "filters-inverted/burn7.png",
  "filters-inverted/burn8.png",
  "filters-inverted/burn9.png",
  "filters-inverted/scratch1.png",
  "filters-inverted/scratch10.png",
  "filters-inverted/scratch11.png",
  "filters-inverted/scratch12.png",
  "filters-inverted/scratch13.png",
  "filters-inverted/scratch14.png",
  "filters-inverted/scratch15.png",
  "filters-inverted/scratch16.png",
  "filters-inverted/scratch17.png",
  "filters-inverted/scratch18.png",
  "filters-inverted/scratch19.png",
  "filters-inverted/scratch2.png",
  "filters-inverted/scratch20.png",
  "filters-inverted/scratch21.png",
  "filters-inverted/scratch22.png",
  "filters-inverted/scratch23.png",
  "filters-inverted/scratch3.png",
  "filters-inverted/scratch4.png",
  "filters-inverted/scratch5.png",
  "filters-inverted/scratch6.png",
  "filters-inverted/scratch7.png",
  "filters-inverted/scratch8.png",
  "filters-inverted/scratch9.png",
  "filters-inverted/vignette-dark.png",
  "filters-inverted/vignette-light.png",
  "filters-inverted/vignette-medium.png",
  "filters-inverted/vignette1.png",
  "filters-inverted/vignette10.png",
  "filters-inverted/vignette11.png",
  "filters-inverted/vignette12.png",
  "filters-inverted/vignette13.png",
  "filters-inverted/vignette14.png",
  "filters-inverted/vignette15.png",
  "filters-inverted/vignette16.png",
  "filters-inverted/vignette17.png",
  "filters-inverted/vignette18.png",
  "filters-inverted/vignette19.png",
  "filters-inverted/vignette2.png",
  "filters-inverted/vignette20.png",
  "filters-inverted/vignette21.png",
  "filters-inverted/vignette22.png",
  "filters-inverted/vignette23.png",
  "filters-inverted/vignette24.png",
  "filters-inverted/vignette25.png",
  "filters-inverted/vignette3.png",
  "filters-inverted/vignette4.png",
  "filters-inverted/vignette5.png",
  "filters-inverted/vignette6.png",
  "filters-inverted/vignette7.png",
  "filters-inverted/vignette8.png",
  "filters-inverted/vignette9.png",
  "filters/border1.png",
  "filters/border10.png",
  "filters/border11.png",
  "filters/border12.png",
  "filters/border13.png",
  "filters/border14.png",
  "filters/border15.png",
  "filters/border16.png",
  "filters/border17.png",
  "filters/border18.png",
  "filters/border19.png",
  "filters/border2.png",
  "filters/border20.png",
  "filters/border21.png",
  "filters/border22.png",
  "filters/border23.png",
  "filters/border24.png",
  "filters/border25.png",
  "filters/border3.png",
  "filters/border4.png",
  "filters/border5.png",
  "filters/border6.png",
  "filters/border7.png",
  "filters/border8.png",
  "filters/border9.png",
  "filters/burn1.png",
  "filters/burn10.png",
  "filters/burn11.png",
  "filters/burn12.png",
  "filters/burn13.png",
  "filters/burn14.png",
  "filters/burn15.png",
  "filters/burn16.png",
  "filters/burn17.png",
  "filters/burn18.png",
  "filters/burn19.png",
  "filters/burn2.png",
  "filters/burn20.png",
  "filters/burn21.png",
  "filters/burn22.png",
  "filters/burn23.png",
  "filters/burn24.png",
  "filters/burn25.png",
  "filters/burn3.png",
  "filters/burn4.png",
  "filters/burn5.png",
  "filters/burn6.png",
  "filters/burn7.png",
  "filters/burn8.png",
  "filters/burn9.png",
  "filters/scratch1.png",
  "filters/scratch10.png",
  "filters/scratch11.png",
  "filters/scratch12.png",
  "filters/scratch13.png",
  "filters/scratch14.png",
  "filters/scratch15.png",
  "filters/scratch16.png",
  "filters/scratch17.png",
  "filters/scratch18.png",
  "filters/scratch19.png",
  "filters/scratch2.png",
  "filters/scratch20.png",
  "filters/scratch21.png",
  "filters/scratch22.png",
  "filters/scratch23.png",
  "filters/scratch3.png",
  "filters/scratch4.png",
  "filters/scratch5.png",
  "filters/scratch6.png",
  "filters/scratch7.png",
  "filters/scratch8.png",
  "filters/scratch9.png",
  "filters/vignette-dark.png",
  "filters/vignette-light.png",
  "filters/vignette-medium.png",
  "filters/vignette1.png",
  "filters/vignette10.png",
  "filters/vignette11.png",
  "filters/vignette12.png",
  "filters/vignette13.png",
  "filters/vignette14.png",
  "filters/vignette15.png",
  "filters/vignette16.png",
  "filters/vignette17.png",
  "filters/vignette18.png",
  "filters/vignette19.png",
  "filters/vignette2.png",
  "filters/vignette20.png",
  "filters/vignette21.png",
  "filters/vignette22.png",
  "filters/vignette23.png",
  "filters/vignette24.png",
  "filters/vignette25.png",
  "filters/vignette3.png",
  "filters/vignette4.png",
  "filters/vignette5.png",
  "filters/vignette6.png",
  "filters/vignette7.png",
  "filters/vignette8.png",
  "filters/vignette9.png"
];

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Limit simultaneous texture downloads on mobile connections.
    let next = 0;
    await Promise.all(Array.from({length: 6}, async () => {
      while (next < ASSETS.length) {
        const path = ASSETS[next++];
        const url = new URL(path, self.registration.scope).href;
        const response = await fetch(url, {cache: 'reload'});
        if (!response.ok) throw new Error('Unable to cache ' + path);
        await cache.put(url, response);
      }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    // Other apps share this GitHub Pages origin: only clean Grungy's caches.
    for (const key of await caches.keys()) {
      if (key.startsWith(PREFIX) && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || !url.href.startsWith(self.registration.scope)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (event.request.mode === 'navigate') {
      // Prefer fresh pages online; use the complete installed version offline.
      try { return await fetch(event.request); }
      catch { return await cache.match(new URL('index.html', self.registration.scope).href); }
    }
    return (await cache.match(event.request, {ignoreSearch: true})) || fetch(event.request);
  })());
});
